// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using Bet.Extensions.AuthorizeNet.Models.V1.Refund.Response;
//
//    var refundTransactionResponse = RefundTransactionResponse.FromJson(jsonString);

namespace Bet.Extensions.AuthorizeNet.Models.V1.Refund.Response
{
    using System;
    using System.Collections.Generic;

    using System.Globalization;

    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    public partial class RefundTransactionResponse
    {
        [JsonProperty("transactionResponse")]
        public TransactionResponse TransactionResponse { get; set; }

        [JsonProperty("refId")]
        [JsonConverter(typeof(ParseStringConverter))]
        public long RefId { get; set; }

        [JsonProperty("messages")]
        public Messages Messages { get; set; }
    }

    public partial class Messages
    {
        [JsonProperty("resultCode")]
        public string ResultCode { get; set; }

        [JsonProperty("message")]
        public MessagesMessage[] Message { get; set; }
    }

    public partial class MessagesMessage
    {
        [JsonProperty("code")]
        public string Code { get; set; }

        [JsonProperty("text")]
        public string Text { get; set; }
    }

    public partial class TransactionResponse
    {
        [JsonProperty("responseCode")]
        [JsonConverter(typeof(ParseStringConverter))]
        public long ResponseCode { get; set; }

        [JsonProperty("authCode")]
        public string AuthCode { get; set; }

        [JsonProperty("avsResultCode")]
        public string AvsResultCode { get; set; }

        [JsonProperty("cvvResultCode")]
        public string CvvResultCode { get; set; }

        [JsonProperty("cavvResultCode")]
        public string CavvResultCode { get; set; }

        [JsonProperty("transId")]
        [JsonConverter(typeof(ParseStringConverter))]
        public long TransId { get; set; }

        [JsonProperty("refTransID")]
        [JsonConverter(typeof(ParseStringConverter))]
        public long RefTransId { get; set; }

        [JsonProperty("transHash")]
        public string TransHash { get; set; }

        [JsonProperty("accountNumber")]
        public string AccountNumber { get; set; }

        [JsonProperty("accountType")]
        public string AccountType { get; set; }

        [JsonProperty("messages")]
        public TransactionResponseMessage[] Messages { get; set; }
    }

    public partial class TransactionResponseMessage
    {
        [JsonProperty("code")]
        [JsonConverter(typeof(ParseStringConverter))]
        public long Code { get; set; }

        [JsonProperty("description")]
        public string Description { get; set; }
    }

    public partial class RefundTransactionResponse
    {
        public static RefundTransactionResponse FromJson(string json) => JsonConvert.DeserializeObject<RefundTransactionResponse>(json, Bet.Extensions.AuthorizeNet.Models.V1.Refund.Response.Converter.Settings);
    }

    public static class Serialize
    {
        public static string ToJson(this RefundTransactionResponse self) => JsonConvert.SerializeObject(self, Bet.Extensions.AuthorizeNet.Models.V1.Refund.Response.Converter.Settings);
    }

    internal static class Converter
    {
        public static readonly JsonSerializerSettings Settings = new JsonSerializerSettings
        {
            MetadataPropertyHandling = MetadataPropertyHandling.Ignore,
            DateParseHandling = DateParseHandling.None,
            Converters =
            {
                new IsoDateTimeConverter { DateTimeStyles = DateTimeStyles.AssumeUniversal }
            },
        };
    }

    internal class ParseStringConverter : JsonConverter
    {
        public override bool CanConvert(Type t) => t == typeof(long) || t == typeof(long?);

        public override object ReadJson(JsonReader reader, Type t, object existingValue, JsonSerializer serializer)
        {
            if (reader.TokenType == JsonToken.Null) return null;
            var value = serializer.Deserialize<string>(reader);
            long l;
            if (Int64.TryParse(value, out l))
            {
                return l;
            }
            throw new Exception("Cannot unmarshal type long");
        }

        public override void WriteJson(JsonWriter writer, object untypedValue, JsonSerializer serializer)
        {
            if (untypedValue == null)
            {
                serializer.Serialize(writer, null);
                return;
            }
            var value = (long)untypedValue;
            serializer.Serialize(writer, value.ToString());
            return;
        }

        public static readonly ParseStringConverter Singleton = new ParseStringConverter();
    }
}
